### ISSUE TITLE
option "double" is not implemented

### ISSUE THREAD

**Issue by don41382** [robertgallup/bmp2hex#3]
Thanks for the great lib, but it looks like "double" is not really implemented.

Or am I wrong?

**Comment by robertgallup** [comment]
Hi Felix,

Thanks for contacting me.

I think it depends on your interpretation of “double”. It’s been awhile since I worked on this, but it looks like “-d” doesn’t actually change the data (i.e. it doesn’t put 8 pixels into a 16-bit word). Rather it just changes data type from uint_8 to uint_16. I should have taken better notes, but I think I added it for compatibility with a graphics library I was using.

Anyway, if you run bmp2hex.py with/without the “-d” option and look at the data type for pixel_data generated in structures, you can see the difference.

Bob

**Comment by don41382** [comment]
Hi Bob,

Thanks for the fast response.

Maybe I am doing something differently, but the option "-d" doesn't seem to change anything. Please try:

``` 
# python bmp2hex.py sobaRGB.bmp | md5
04916535424e6cf1994e1664ec8e45c0
```

```
python bmp2hex.py -d sobaRGB.bmp | md5
04916535424e6cf1994e1664ec8e45c0
```

**Comment by robertgallup** [comment]
Hi Felix,

I’m not near my computer right now, but I’ll try this later.

In the meantime, look at your output when you try this test yourself. Along with the actual data bytes is a struct defining the data structure. One of the elements of that structure is “pixel_data[]”. Is the definition of that element the same with and without “-d”? (you can see the struct in the first example in the readme)

Without “-d”, pixel_data[] should be of type uint8_t. With “-d”, the type should be uint16_t. 

Bob

On Jul 21, 2019, at 11:04 AM, Felix Eckhardt <notifications@github.com> wrote:

Hi Bob,

Thanks for the fast response.

Maybe I am doing something differently, but the option "-d" doesn't seem to change anything. Please try:

# python bmp2hex.py sobaRGB.bmp | md5
04916535424e6cf1994e1664ec8e45c0
# ```

```python bmp2hex.py -d sobaRGB.bmp | md5
04916535424e6cf1994e1664ec8e45c0
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by robertgallup** [comment]
Hi Felix,

Thanks to your persistence, I found a problem with -d when not using “named” structures (i.e. when “-n” isn’t used. As you pointed out, “-d” was being ignored. So, I’ve just pushed an update that should fix the problem. Below is the output I *now* get. You can see the pixel_data declaration differs between two. Let me know if I missed something.

:-)

Cheers,
Bob




python bmp2hex.py soba.bmp

PROGMEM const struct {
  unsigned int   width;
  unsigned int   height;
  unsigned int   bitDepth;
  uint8_t   *pixel_data[160];
} SOBA = {
40, 32, 1, {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x01, 0x90, 0x00, 0x00, 0x00, 0x03, 0x30, 0x00, 0x00,
0x00, 0x06, 0x60, 0x00, 0x00, 0x00, 0x0c, 0xc0, 0x00, 0x00, 0x00, 0x19, 0x80, 0x00, 0x1f, 0x00,
0x33, 0x00, 0x00, 0x7b, 0xc0, 0x66, 0x00, 0x01, 0xe0, 0xf0, 0xcc, 0x00, 0x03, 0x80, 0x39, 0x98,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0xff, 0xff, 0xff, 0xe0, 0x07, 0xff, 0xff, 0xff, 0xe0,
0x07, 0xff, 0xff, 0xff, 0xe0, 0x07, 0xff, 0xff, 0xff, 0xe0, 0x07, 0xff, 0xff, 0xff, 0xe0, 0x03,
0xff, 0xff, 0xff, 0xc0, 0x03, 0xff, 0xff, 0xff, 0xc0, 0x01, 0xff, 0xff, 0xff, 0x80, 0x01, 0xff,
0xff, 0xff, 0x80, 0x00, 0xff, 0xff, 0xff, 0x00, 0x00, 0x7f, 0xff, 0xfe, 0x00, 0x00, 0x3f, 0xff,
0xfc, 0x00, 0x00, 0x1f, 0xff, 0xf8, 0x00, 0x00, 0x0f, 0xff, 0xf0, 0x00, 0x00, 0x03, 0xff, 0xc0,
0x00, 0x00, 0x01, 0xff, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
};



python bmp2hex.py -d soba.bmp

PROGMEM const struct {
  unsigned int   width;
  unsigned int   height;
  unsigned int   bitDepth;
  uint16_t  *pixel_data[160];
} SOBA = {
40, 32, 1, {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x01, 0x90, 0x00, 0x00, 0x00, 0x03, 0x30, 0x00, 0x00,
0x00, 0x06, 0x60, 0x00, 0x00, 0x00, 0x0c, 0xc0, 0x00, 0x00, 0x00, 0x19, 0x80, 0x00, 0x1f, 0x00,
0x33, 0x00, 0x00, 0x7b, 0xc0, 0x66, 0x00, 0x01, 0xe0, 0xf0, 0xcc, 0x00, 0x03, 0x80, 0x39, 0x98,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0xff, 0xff, 0xff, 0xe0, 0x07, 0xff, 0xff, 0xff, 0xe0,
0x07, 0xff, 0xff, 0xff, 0xe0, 0x07, 0xff, 0xff, 0xff, 0xe0, 0x07, 0xff, 0xff, 0xff, 0xe0, 0x03,
0xff, 0xff, 0xff, 0xc0, 0x03, 0xff, 0xff, 0xff, 0xc0, 0x01, 0xff, 0xff, 0xff, 0x80, 0x01, 0xff,
0xff, 0xff, 0x80, 0x00, 0xff, 0xff, 0xff, 0x00, 0x00, 0x7f, 0xff, 0xfe, 0x00, 0x00, 0x3f, 0xff,
0xfc, 0x00, 0x00, 0x1f, 0xff, 0xf8, 0x00, 0x00, 0x0f, 0xff, 0xf0, 0x00, 0x00, 0x03, 0xff, 0xc0,
0x00, 0x00, 0x01, 0xff, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
};

**Comment by don41382** [comment]
Thanks @robertgallup! Just to get it right, the result is still not a uint16_t, correct?

**Comment by robertgallup** [comment]
Hi Felix,

In looking into this further, I noticed some other type issues with the “-d” result. I just pushed another version with some more changes. Does this address your most recent question? If not, if you could supply some sample output showing what you mean, that would be great.

Cheers,
Bob

**Comment by don41382** [comment]
Hey Robert,

sorry for the late answer.

The problem is that uint16_t should be represented by 2 bytes, which means each hex number should look like 0xFF and if it's just uint8_t it should just have 1 byte. Right now, they are the same.

Do you know what I mean? The representation of the raw hex data should vary depending on the type.

Cheers,
Felix

**Comment by robertgallup** [comment]
Hi Felix,

Sorry for *my* late answer!

You're saying a uint16 should be represented by two bytes rather than one (e.g. 0xFFFF rather than 0xFF, 0xFF). I see what you mean.

So, do you have an application for this parameter? Or, did you just notice the implementation didn't seem right? I can't remember why I added it in the first place. And I feel like without a specific application it may be difficult to understand how it's best implemented and I'd be inclined to remove it.

Thanks,
Bob

**Comment by robertgallup** [comment]
Closed for now. If there's a compelling use case, we could revisit this issue.
